# Generated by Django 3.2.2 on 2021-08-05 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_entry_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
