# Generated by Django 3.2.2 on 2021-05-18 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_reviewed', models.DateField()),
                ('review_frequency', models.IntegerField()),
                ('category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_reviewed', models.DateField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.field')),
            ],
        ),
    ]
