# Generated by Django 3.2.2 on 2021-05-18 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='category',
        ),
    ]
