# Generated by Django 3.2 on 2021-05-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_remove_field_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='new',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
