# Generated by Django 3.2 on 2021-05-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_field_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='new',
        ),
    ]
