# Generated by Django 3.2.2 on 2021-06-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_remove_field_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='last_reviewed',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='review_frequency',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='last_reviewed',
            field=models.DateField(auto_now=True),
        ),
    ]
