# Generated by Django 3.2.2 on 2021-07-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0006_field_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='last_reviewed',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='last_reviewed',
            field=models.DateField(),
        ),
    ]
