# Generated by Django 3.2.2 on 2021-07-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0007_auto_20210715_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='last_reviewed',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='topic',
            name='last_reviewed',
            field=models.DateField(default=None),
        ),
    ]
