# Generated by Django 3.2.2 on 2021-07-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0008_auto_20210715_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='last_reviewed',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='last_reviewed',
            field=models.DateField(default=None, null=True),
        ),
    ]
