# Generated by Django 3.2.2 on 2021-07-15 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0008_auto_20210715_1245'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='active',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='topic',
        ),
        migrations.AddField(
            model_name='revision',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='garden.field'),
            preserve_default=False,
        ),
    ]
